services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.4.2
    container_name: rocketchat
    platform: linux/amd64  # Forzamos la plataforma para que funcione en ARM64
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ROOT_URL=${ROOT_URL}
      - PORT=3000
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:5
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
