version: '3.7'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.1.0
    restart: always
    environment:
      - PORT=3000
      - ROOT_URL=https://archk-qa-roocket-app-1.ql357b.easypanel.host/
      - MONGO_URL=mongodb://rocketchat:password@mongo:27017/rocketchat?authSource=admin
      - MONGO_OPLOG_URL=mongodb://rocketchat:password@mongo:27017/local?authSource=admin
    ports:
      - "80:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rocketchat
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongo_data:
