version: "3.8"

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.4.2
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - PORT=3001
      - ROOT_URL=https://archk-qa-roocket-app-1.ql357b.easypanel.host
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - DEPLOY_METHOD=docker
      - DEPLOY_PLATFORM=easyPanel
    depends_on:
      - mongo
    ports:
      - "3001:3000" # Evitamos conflicto usando 3001 en el host

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
