services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.8.1
    platform: linux/amd64
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - easypanel-archk-qa

  mongo:
    image: mongo:5
    volumes:
      - mongo_data:/data/db
    networks:
      - easypanel-archk-qa

volumes:
  mongo_data:

networks:
  easypanel-archk-qa:
    external: true
